import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AutomationPage } from "@/components/banking/automation-page";
import { AlertResolutionForm, OverdraftChangeForm, OverdraftDecisionForm, OverdraftStatusForm } from "@/components/banking/operations-forms";
import { formatDate, formatMoney, labelEnum } from "@/components/banking/format";
import { Badge, Breadcrumbs, Panel, StatusRegion } from "@/components/banking/ui";
import { decideOverdraftAction, requestOverdraftLimitChangeAction, resolveOverdraftAlertAction, setOverdraftStatusAction } from "@/modules/actions/overdrafts";
import { getOverdraftFacility, listWorkQueue } from "@/modules/operations-queries";

export const metadata: Metadata = { title: "Overdraft facility" };

export default async function OverdraftFacilityPage({ params }: { params: Promise<{ reference: string }> }) {
  const { reference } = await params;
  const [facility, work] = await Promise.all([getOverdraftFacility(reference), listWorkQueue()]);
  if (!facility) notFound();
  const approval = work.find((item) => item.entityType === "OVERDRAFT" && item.entityReference === reference && ["OPEN", "ASSIGNED"].includes(item.status));
  const change = requestOverdraftLimitChangeAction.bind(null, reference);
  const status = setOverdraftStatusAction.bind(null, reference);
  return <AutomationPage name="overdraft-facility-detail"><Breadcrumbs items={[{ label: "Arranged overdrafts", href: "/overdrafts" }, { label: reference }]} />
    <section className="record-banner" data-bp="overdraft-record-header"><div><p>Arranged overdraft · {facility.currency}</p><h1>{facility.reference}</h1></div><div className="record-banner-meta"><span className="mono">{facility.accountNumber}</span><Badge tone={facility.status === "ACTIVE" ? "positive" : facility.status === "SUSPENDED" || facility.status === "DECLINED" ? "negative" : "warning"}>{labelEnum(facility.status)}</Badge></div></section>
    {facility.status === "SUSPENDED" ? <StatusRegion id="overdraft-suspended" tone="warning">Further drawing is suspended; existing debt remains payable.</StatusRegion> : null}
    <div className="metrics-grid"><div className="metric" data-bp="overdraft-metric-limit"><span>Approved limit</span><strong>{formatMoney(facility.approvedLimit, facility.currency)}</strong><small>Requested {formatMoney(facility.requestedLimit, facility.currency)}</small></div><div className="metric" data-bp="overdraft-metric-utilization"><span>Utilization</span><strong>{formatMoney(facility.utilization, facility.currency)}</strong><small>max(0, negative ledger balance)</small></div><div className="metric" data-bp="overdraft-metric-holds"><span>Active holds</span><strong>{formatMoney(facility.activeHolds, facility.currency)}</strong><small>Pending payment reservations</small></div><div className="metric" data-bp="overdraft-metric-headroom"><span>Headroom</span><strong>{formatMoney(facility.headroom, facility.currency)}</strong><small>Limit less utilization and holds</small></div><div className="metric" data-bp="overdraft-metric-interest"><span>Estimated daily interest</span><strong>{formatMoney(facility.estimatedDailyInterest, facility.currency)}</strong><small>{facility.annualInterestRate}% annual demo price</small></div></div>
    <div className="two-column"><Panel title="Facility terms"><dl className="definition-grid"><div><dt>Account</dt><dd><Link href={`/accounts/${facility.accountNumber}`} data-bp="overdraft-account-link">{facility.accountNumber}</Link></dd></div><div><dt>Customer</dt><dd><Link href={`/customers/${facility.customerNumber}`}>{facility.customerNumber} · {facility.customerName}</Link></dd></div><div><dt>Purpose</dt><dd>{facility.purpose}</dd></div><div><dt>Risk grade</dt><dd>{facility.riskGrade}</dd></div><div><dt>Start date</dt><dd>{facility.startDate ? formatDate(facility.startDate) : "—"}</dd></div><div><dt>Review date</dt><dd>{facility.reviewDate ? formatDate(facility.reviewDate) : "—"}</dd></div><div><dt>Expiry date</dt><dd>{facility.expiryDate ? formatDate(facility.expiryDate) : "—"}</dd></div><div><dt>Version</dt><dd>{facility.version}</dd></div></dl></Panel><Panel title="Affordability information" description="Fictional application metadata"><pre className="json-view" data-bp="overdraft-affordability">{JSON.stringify(facility.affordabilityInformation, null, 2)}</pre></Panel></div>
    {approval ? <Panel title="Independent decision" description="Maker and checker must be different users"><OverdraftDecisionForm action={decideOverdraftAction} facilityReference={reference} workItem={approval} /></Panel> : null}
    {facility.status === "ACTIVE" ? <div className="two-column"><Panel title="Limit change"><OverdraftChangeForm action={change} currentLimit={facility.approvedLimit} /></Panel><Panel title="Suspend or close"><OverdraftStatusForm action={status} /></Panel></div> : null}
    <Panel title={`Monitoring alerts (${facility.alerts.length})`}><table className="data-table" data-bp="overdraft-alert-table"><thead><tr><th>Reference</th><th>Type</th><th>Severity</th><th>Status</th><th>Detected</th><th>Due</th><th>Details</th><th>Intervention</th></tr></thead><tbody>{facility.alerts.map((alert) => <tr key={alert.reference}><td className="mono">{alert.reference}</td><td>{labelEnum(alert.type)}</td><td><Badge tone={alert.severity === "CRITICAL" ? "negative" : "warning"}>{labelEnum(alert.severity)}</Badge></td><td>{labelEnum(alert.status)}</td><td>{formatDate(alert.detectedAt, true)}</td><td>{formatDate(alert.dueAt, true)}</td><td>{alert.details}</td><td>{alert.intervention ? labelEnum(alert.intervention) : "—"}</td></tr>)}</tbody></table>{facility.alerts.filter((alert) => alert.status !== "RESOLVED").map((alert) => <AlertResolutionForm key={alert.reference} action={resolveOverdraftAlertAction.bind(null, alert.reference)} alertReference={alert.reference} />)}</Panel>
    <Panel title="Limit history"><table className="data-table" data-bp="overdraft-limit-history-table"><thead><tr><th>Effective date</th><th className="numeric">Previous limit</th><th className="numeric">New limit</th><th>Reason</th><th>Approver</th></tr></thead><tbody>{facility.limitHistory.map((item, index) => <tr key={`${item.effectiveDate}-${index}`}><td>{formatDate(item.effectiveDate)}</td><td className="numeric">{formatMoney(item.previousLimit, facility.currency)}</td><td className="numeric">{formatMoney(item.newLimit, facility.currency)}</td><td>{item.reason}</td><td className="mono">{item.approvedBy}</td></tr>)}</tbody></table></Panel>
  </AutomationPage>;
}
