import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AccountStatusForm } from "@/components/banking/action-forms";
import { AutomationPage } from "@/components/banking/automation-page";
import { formatDate, formatMoney, labelEnum } from "@/components/banking/format";
import { Badge, Breadcrumbs, Panel, StatusRegion } from "@/components/banking/ui";
import { updateAccountStatusAction } from "@/modules/actions/banking";
import { defaultStatementPeriod } from "@/modules/domain/statement-policy";
import { getAccount } from "@/modules/queries";

export const metadata: Metadata = { title: "Account details" };

export default async function AccountDetailPage({ params }: { params: Promise<{ accountNumber: string }> }) {
  const { accountNumber } = await params;
  const account = await getAccount(accountNumber);
  if (!account) notFound();
  const statusAction = updateAccountStatusAction.bind(null, accountNumber);
  const statementPeriod = defaultStatementPeriod();
  const statementHref = `/accounts/${account.accountNumber}/statement?from=${statementPeriod.fromDate}&to=${statementPeriod.toDate}`;

  return <AutomationPage name="account-detail">
    <Breadcrumbs items={[{ label: "Accounts", href: "/accounts" }, { label: account.accountNumber }]} />
    <section className="record-banner" data-bp="account-record-header"><div><p>{labelEnum(account.kind)} · {account.currency}</p><h1>{account.productName}</h1></div><div className="record-banner-meta"><span className="mono">{account.accountNumber}</span><Badge tone={account.status === "ACTIVE" ? "positive" : "warning"}>{labelEnum(account.status)}</Badge></div></section>
    {account.readOnly ? <StatusRegion id="account-read-only" tone="warning">This is a seeded loan facility. Details and repayments are read-only.</StatusRegion> : null}
    <div className="two-column">
      <Panel title="Account summary"><div className="equal-columns"><div className="account-balance"><span>Available balance</span><strong>{formatMoney(account.availableBalance, account.currency)}</strong></div><div className="account-balance"><span>Ledger balance</span><strong>{formatMoney(account.balance, account.currency)}</strong></div></div><dl className="definition-grid" style={{ marginTop: 18 }}><div><dt>Account number</dt><dd className="mono">{account.accountNumber}</dd></div><div><dt>Customer</dt><dd><Link href={`/customers/${account.customerNumber}`} data-bp="account-customer-link">{account.customerName}</Link></dd></div><div><dt>Customer number</dt><dd className="mono">{account.customerNumber}</dd></div><div><dt>Product code</dt><dd className="mono">{account.productCode}</dd></div><div><dt>Branch</dt><dd>{account.branchCode}</dd></div><div><dt>Opened</dt><dd>{formatDate(account.openedAt)}</dd></div><div><dt>Nickname</dt><dd>{account.nickname || "—"}</dd></div><div><dt>Overdraft limit</dt><dd>{account.overdraft ? formatMoney(account.overdraft.approvedLimit, account.currency) : "Not arranged"}</dd></div><div><dt>Maturity</dt><dd>{account.maturityDate ? formatDate(account.maturityDate) : "—"}</dd></div></dl><div className="form-actions"><a className="secondary-button" href={statementHref} data-bp="account-statement-download" download>Download 90-day CSV statement</a></div></Panel>
      <Panel title="Account maintenance" description="Every change is written to the audit trail"><AccountStatusForm action={statusAction} currentStatus={account.status} readOnly={account.readOnly} /></Panel>
    </div>
    {account.overdraft ? <Panel title="Arranged overdraft" description="Operational facility source of truth"><div className="metrics-grid"><div className="metric" data-bp="account-overdraft-limit"><span>Approved limit</span><strong>{formatMoney(account.overdraft.approvedLimit, account.currency)}</strong><small>{labelEnum(account.overdraft.status)}</small></div><div className="metric" data-bp="account-overdraft-utilization"><span>Utilization</span><strong>{formatMoney(account.overdraft.utilization, account.currency)}</strong><small>Negative ledger balance</small></div><div className="metric" data-bp="account-overdraft-holds"><span>Active holds</span><strong>{formatMoney(account.overdraft.activeHolds, account.currency)}</strong><small>Reserved pending payments</small></div><div className="metric" data-bp="account-overdraft-headroom"><span>Headroom</span><strong>{formatMoney(account.overdraft.headroom, account.currency)}</strong><small>Available arranged borrowing</small></div><div className="metric" data-bp="account-overdraft-interest"><span>Daily interest estimate</span><strong>{formatMoney(account.overdraft.estimatedDailyInterest, account.currency)}</strong><small>{account.overdraft.annualInterestRate}% annual demo rate</small></div></div><dl className="definition-grid"><div><dt>Facility</dt><dd><Link href={`/overdrafts/${account.overdraft.reference}`} data-bp="account-overdraft-link">{account.overdraft.reference}</Link></dd></div><div><dt>Review date</dt><dd>{account.overdraft.reviewDate ? formatDate(account.overdraft.reviewDate) : "—"}</dd></div><div><dt>Expiry</dt><dd>{account.overdraft.expiryDate ? formatDate(account.overdraft.expiryDate) : "—"}</dd></div><div><dt>Repeat-use alerts</dt><dd>{account.overdraft.alerts.filter((alert) => alert.status !== "RESOLVED").length}</dd></div></dl>{account.overdraft.alerts.length ? <table className="data-table" data-bp="account-overdraft-alert-table"><thead><tr><th>Reference</th><th>Type</th><th>Status</th><th>Severity</th><th>Details</th></tr></thead><tbody>{account.overdraft.alerts.map((alert) => <tr key={alert.reference}><td className="mono">{alert.reference}</td><td>{labelEnum(alert.type)}</td><td>{labelEnum(alert.status)}</td><td>{labelEnum(alert.severity)}</td><td>{alert.details}</td></tr>)}</tbody></table> : null}</Panel> : null}
    {account.loan ? <Panel title="Loan schedule" description={`Outstanding principal ${formatMoney(account.loan.outstandingPrincipal, account.currency)} · rate ${account.loan.interestRate}% · next payment ${formatDate(account.loan.nextPaymentDate)}`}><div style={{ margin: "-16px" }}><table className="data-table" data-bp="loan-repayment-table"><thead><tr><th>Due date</th><th>Paid date</th><th className="numeric">Principal</th><th className="numeric">Interest</th><th>Status</th></tr></thead><tbody>{account.loan.repayments.map((repayment) => <tr key={repayment.dueDate}><td>{formatDate(repayment.dueDate)}</td><td>{repayment.paidAt ? formatDate(repayment.paidAt) : "—"}</td><td className="numeric">{formatMoney(repayment.principal, account.currency)}</td><td className="numeric">{formatMoney(repayment.interest, account.currency)}</td><td><Badge tone={repayment.status === "PAID" ? "positive" : "warning"}>{labelEnum(repayment.status)}</Badge></td></tr>)}</tbody></table></div></Panel> : null}
    <Panel title={`Transaction history (${account.transactions.length})`} description="Most recent booked and pending movements"><div style={{ margin: "-16px" }}><table className="data-table" data-bp="account-transactions-table"><thead><tr><th>Booking date</th><th>Reference</th><th>Description</th><th>Counterparty</th><th>Status</th><th className="numeric">Debit</th><th className="numeric">Credit</th><th className="numeric">Balance</th></tr></thead><tbody>{account.transactions.map((transaction) => <tr key={transaction.reference} data-bp={`transaction-row-${transaction.reference}`}><td>{formatDate(transaction.bookedAt)}</td><td className="mono">{transaction.reference}</td><td>{transaction.description}</td><td>{transaction.counterparty || "—"}</td><td><Badge tone={transaction.status === "BOOKED" ? "positive" : "warning"}>{labelEnum(transaction.status)}</Badge></td><td className="numeric">{transaction.direction === "DEBIT" ? formatMoney(transaction.amount, transaction.currency) : "—"}</td><td className="numeric">{transaction.direction === "CREDIT" ? formatMoney(transaction.amount, transaction.currency) : "—"}</td><td className="numeric">{formatMoney(transaction.balanceAfter, transaction.currency)}</td></tr>)}</tbody></table></div></Panel>
  </AutomationPage>;
}
