import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AutomationPage } from "@/components/banking/automation-page";
import { EvidenceVerificationForm, KycDecisionForm, SimpleKycActionForm } from "@/components/banking/operations-forms";
import { formatDate, formatMoney, labelEnum } from "@/components/banking/format";
import { Badge, Breadcrumbs, Panel, StatusRegion } from "@/components/banking/ui";
import { decideKycCaseAction, runScreeningAction, submitKycCaseAction, verifyKycEvidenceAction } from "@/modules/actions/kyc";
import { getKycCase, listWorkQueue } from "@/modules/operations-queries";

export const metadata: Metadata = { title: "KYC case workspace" };

export default async function KycCasePage({ params }: { params: Promise<{ reference: string }> }) {
  const { reference } = await params;
  const [kycCase, approvalItems] = await Promise.all([getKycCase(reference), listWorkQueue({ type: "KYC_APPROVAL" })]);
  if (!kycCase) notFound();
  const approval = approvalItems.find((item) => item.entityReference === reference && ["OPEN", "ASSIGNED"].includes(item.status));
  const runScreening = runScreeningAction.bind(null, reference);
  const submitKyc = submitKycCaseAction.bind(null, reference);
  const verifyEvidence = verifyKycEvidenceAction.bind(null, reference);
  return <AutomationPage name="kyc-case-workspace"><Breadcrumbs items={[{ label: "KYC operations", href: "/kyc" }, { label: reference }]} />
    <section className="record-banner" data-bp="kyc-case-record-header"><div><p>{labelEnum(kycCase.type)} · {kycCase.jurisdiction}</p><h1>{kycCase.customerName}</h1></div><div className="record-banner-meta"><span className="mono">{reference}</span><Badge tone={kycCase.status === "APPROVED" ? "positive" : kycCase.status === "REJECTED" ? "negative" : "warning"}>{labelEnum(kycCase.status)}</Badge><Badge tone={kycCase.riskRating === "HIGH" ? "negative" : "warning"}>{labelEnum(kycCase.riskRating)} risk</Badge></div></section>
    <StatusRegion id="kyc-fictional-notice">Screening data and evidence references are fictional and must not be used for real compliance decisions.</StatusRegion>
    <nav className="record-tabs" aria-label="KYC case sections" data-bp="kyc-case-sections"><a href="#profile">Profile</a><a href="#risk">Risk</a><a href="#screening">Screening</a><a href="#evidence">Evidence</a><a href="#ownership">Ownership</a><a href="#decision">Decision</a></nav>
    <section id="profile"><Panel title="Profile" description="Purpose, activity and source information"><dl className="definition-grid">{kycCase.profile ? <><div><dt>Account purpose</dt><dd>{kycCase.profile.accountPurpose}</dd></div><div><dt>Occupation / business</dt><dd>{kycCase.profile.occupationOrBusiness}</dd></div><div><dt>Expected credits</dt><dd>{formatMoney(kycCase.profile.expectedMonthlyCredits)}</dd></div><div><dt>Expected debits</dt><dd>{formatMoney(kycCase.profile.expectedMonthlyDebits)}</dd></div><div><dt>Expected countries</dt><dd>{kycCase.profile.expectedCountries.join(", ")}</dd></div><div><dt>Cash usage</dt><dd>{kycCase.profile.cashUsage}</dd></div><div><dt>Source of funds</dt><dd>{kycCase.profile.sourceOfFunds}</dd></div><div><dt>Source of wealth</dt><dd>{kycCase.profile.sourceOfWealth}</dd></div></> : <div><dt>Status</dt><dd>CDD profile not recorded</dd></div>}</dl></Panel></section>
    <section id="risk"><Panel title="Risk assessment" description={`Calculated score ${kycCase.riskScore}; FutureBank demo bands: low 0–24, medium 25–49, high 50+`}><table className="data-table" data-bp="kyc-risk-table"><thead><tr><th>Category</th><th>Rule</th><th className="numeric">Score</th><th>Explanation</th></tr></thead><tbody>{kycCase.riskFactors.map((factor, index) => <tr key={`${factor.rule}-${index}`}><td>{factor.category}</td><td>{labelEnum(factor.rule)}</td><td className="numeric">{factor.score}</td><td>{factor.explanation}</td></tr>)}</tbody></table>{kycCase.overrideReason ? <StatusRegion id="kyc-risk-override" tone="warning">Manual override: {kycCase.overrideReason}</StatusRegion> : null}</Panel></section>
    <section id="screening"><Panel title="Fictional screening" description="Sanctions, PEP and adverse-media checks"><table className="data-table" data-bp="kyc-screening-table"><thead><tr><th>Reference</th><th>Subject</th><th>Type</th><th>Score</th><th>Outcome</th><th>Resolution</th></tr></thead><tbody>{kycCase.screenings.map((check) => <tr key={check.reference}><td className="mono">{check.reference}</td><td>{check.subjectName}</td><td>{labelEnum(check.screeningType)}</td><td className="numeric">{check.matchScore}</td><td><Badge tone={check.outcome === "CONFIRMED_MATCH" ? "negative" : check.outcome === "POSSIBLE_MATCH" ? "warning" : "positive"}>{labelEnum(check.outcome)}</Badge></td><td>{check.resolutionComment ?? "—"}</td></tr>)}</tbody></table>{["OPEN", "IN_PROGRESS", "AWAITING_INFORMATION"].includes(kycCase.status) ? <SimpleKycActionForm action={runScreening} bp="kyc-run-screening" label="Run fictional screening" intent="run-screening" /> : null}</Panel></section>
    <section id="evidence"><Panel title="Evidence" description="Metadata only; no document uploads"><table className="data-table" data-bp="kyc-evidence-table"><thead><tr><th>Reference</th><th>Requirement</th><th>Document reference</th><th>Document number</th><th>Issued</th><th>Expires</th><th>First name</th><th>Last name</th><th>Verification</th><th>Notes</th></tr></thead><tbody>{kycCase.evidence.map((item) => <tr key={item.reference}><td className="mono">{item.reference}</td><td>{labelEnum(item.evidenceType)}</td><td className="mono">{item.documentReference}</td><td className="mono">{item.documentNumber ?? "—"}</td><td>{item.issuedAt ? formatDate(item.issuedAt) : "—"}</td><td>{item.expiresAt ? formatDate(item.expiresAt) : "—"}</td><td>{item.firstName ?? "—"}</td><td>{item.lastName ?? "—"}</td><td><Badge tone={item.verificationStatus === "VERIFIED" ? "positive" : item.verificationStatus === "REJECTED" || item.verificationStatus === "EXPIRED" ? "negative" : "warning"}>{labelEnum(item.verificationStatus)}</Badge></td><td>{item.reviewerNotes ?? "—"}</td></tr>)}</tbody></table>{["OPEN", "IN_PROGRESS", "AWAITING_INFORMATION"].includes(kycCase.status) ? <EvidenceVerificationForm action={verifyEvidence} evidenceReferences={kycCase.evidence.map((item) => item.reference)} /> : null}</Panel></section>
    <section id="ownership"><Panel title="Ownership and restrictions"><p><Link href={`/customers/${kycCase.customerNumber}?tab=relationships`} data-bp="kyc-customer-ownership-link">Open customer ownership and relationship record</Link></p><table className="data-table" data-bp="kyc-restrictions-table"><thead><tr><th>Reference</th><th>Restriction</th><th>Reason</th><th>Effective</th><th>Active</th></tr></thead><tbody>{kycCase.restrictions.map((item) => <tr key={item.reference}><td className="mono">{item.reference}</td><td>{labelEnum(item.type)}</td><td>{item.reason}</td><td>{formatDate(item.effectiveFrom, true)}</td><td>{item.active ? "Yes" : "No"}</td></tr>)}</tbody></table></Panel></section>
    <section id="decision"><Panel title="Decision" description="Maker and checker must be different users">{approval ? <KycDecisionForm action={decideKycCaseAction} caseReference={reference} workItem={approval} /> : ["OPEN", "IN_PROGRESS", "AWAITING_INFORMATION"].includes(kycCase.status) ? <SimpleKycActionForm action={submitKyc} bp="kyc-submit" label="Submit for Compliance approval" intent="submit-kyc" /> : <StatusRegion id="kyc-decision-complete" tone={kycCase.status === "APPROVED" ? "success" : "warning"}>Case decision: {labelEnum(kycCase.status)}.</StatusRegion>}</Panel></section>
  </AutomationPage>;
}
