import type { StaffRole } from "@/modules/contracts";

export type StaffPermission =
  | "CUSTOMER_MAINTAIN"
  | "KYC_GATHER"
  | "KYC_SCREEN"
  | "KYC_DECIDE"
  | "RESTRICTION_MAINTAIN"
  | "PAYMENT_INITIATE"
  | "PAYMENT_DECIDE"
  | "PAYMENT_REVERSAL_INITIATE"
  | "PAYMENT_REVERSAL_DECIDE"
  | "PAYMENT_INSTRUCTION_MAINTAIN"
  | "PAYMENT_SCHEDULE_EXECUTE"
  | "END_OF_DAY_EXECUTE"
  | "RECONCILIATION_EXECUTE"
  | "RECONCILIATION_RESOLVE"
  | "ACCOUNTING_PERIOD_CLOSE_INITIATE"
  | "ACCOUNTING_PERIOD_CLOSE_DECIDE"
  | "GENERAL_LEDGER_JOURNAL_INITIATE"
  | "GENERAL_LEDGER_JOURNAL_DECIDE"
  | "LOAN_ORIGINATION_INITIATE"
  | "LOAN_ORIGINATION_DECIDE"
  | "DIRECT_DEBIT_MAINTAIN"
  | "DIRECT_DEBIT_COLLECT"
  | "OVERDRAFT_INITIATE"
  | "OVERDRAFT_DECIDE"
  | "OVERDRAFT_ALERT_RESOLVE"
  | "DEMO_RESET";

const permissions: Record<StaffRole, readonly StaffPermission[]> = {
  OPERATOR: ["CUSTOMER_MAINTAIN", "KYC_GATHER", "KYC_SCREEN", "PAYMENT_INITIATE", "PAYMENT_REVERSAL_INITIATE", "PAYMENT_INSTRUCTION_MAINTAIN", "DIRECT_DEBIT_MAINTAIN", "DIRECT_DEBIT_COLLECT", "OVERDRAFT_INITIATE", "LOAN_ORIGINATION_INITIATE"],
  SUPERVISOR: ["PAYMENT_DECIDE", "PAYMENT_REVERSAL_DECIDE", "PAYMENT_SCHEDULE_EXECUTE", "END_OF_DAY_EXECUTE", "RECONCILIATION_EXECUTE", "RECONCILIATION_RESOLVE", "ACCOUNTING_PERIOD_CLOSE_INITIATE", "GENERAL_LEDGER_JOURNAL_INITIATE", "OVERDRAFT_DECIDE", "OVERDRAFT_ALERT_RESOLVE", "LOAN_ORIGINATION_DECIDE"],
  COMPLIANCE: ["KYC_DECIDE", "RESTRICTION_MAINTAIN"],
  ADMIN: ["CUSTOMER_MAINTAIN", "KYC_GATHER", "KYC_SCREEN", "KYC_DECIDE", "RESTRICTION_MAINTAIN", "PAYMENT_INITIATE", "PAYMENT_DECIDE", "PAYMENT_REVERSAL_INITIATE", "PAYMENT_REVERSAL_DECIDE", "PAYMENT_INSTRUCTION_MAINTAIN", "PAYMENT_SCHEDULE_EXECUTE", "END_OF_DAY_EXECUTE", "RECONCILIATION_EXECUTE", "RECONCILIATION_RESOLVE", "ACCOUNTING_PERIOD_CLOSE_DECIDE", "GENERAL_LEDGER_JOURNAL_DECIDE", "DIRECT_DEBIT_MAINTAIN", "DIRECT_DEBIT_COLLECT", "OVERDRAFT_INITIATE", "OVERDRAFT_DECIDE", "OVERDRAFT_ALERT_RESOLVE", "LOAN_ORIGINATION_INITIATE", "LOAN_ORIGINATION_DECIDE", "DEMO_RESET"],
};

export function hasRequiredRole(actual: StaffRole, required: StaffRole): boolean {
  return actual === "ADMIN" || actual === required;
}

export function hasPermission(role: StaffRole, permission: StaffPermission): boolean {
  return permissions[role].includes(permission);
}
